wang/pages/urls.py
#AUTHORS:

#Gabriel Lizano Alvarado
#Edwin Lobo Sánchez 
#Ruben Pereira Ugalde
#Luis Guillermo Ramírez Díaz

from django.urls import path
from django.conf.urls import url
from . import views

urlpatterns = [

    path('ajax/request', views.request, name='request'),
    path('ajax/request_all_tree', views.request_all_tree, name='request_all_tree'),
    path('page_deductions', views.page_deductions, name='page_deductions'),
    url(r'([^/]*)', views.index, name='index'),

]

wang/wang/urls.py
#AUTHORS:

#Gabriel Lizano Alvarado
#Edwin Lobo Sánchez 
#Ruben Pereira Ugalde
#Luis Guillermo Ramírez Díaz

"""wang URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url('admin/', admin.site.urls),
	url(r'^', include('pages.urls'))
]

wang/pages/models.py
#AUTHORS:

#Gabriel Lizano Alvarado
#Edwin Lobo Sánchez 
#Ruben Pereira Ugalde
#Luis Guillermo Ramírez Díaz

from django.db import models

# Create your models here.

TYPE_CHOICES = (
    ('1', 'WANG'),
    ('2', 'LORÍA'),
)

class Page(models.Model):
    title = models.CharField(max_length=60)
    permalink = models.CharField(max_length=12, unique=True)
    update_date = models.DateTimeField('Last Updated')
    bodytext = models.TextField('Page Content', blank=True)

    def __str__(self):
        return self.title

# Models to connect to the Web API.

class deduction(models.Model):
    created = models.DateTimeField(auto_now_add = True)
    formula = models.CharField(max_length = 200)
    resolve_type = models.CharField(max_length = 20, choices = TYPE_CHOICES)
    
    def __str__(self):
        return f"{self.formula} {self.resolve_type}"

wang/pages/forms.py
#AUTHORS:

#Gabriel Lizano Alvarado
#Edwin Lobo Sánchez 
#Ruben Pereira Ugalde
#Luis Guillermo Ramírez Díaz

from django import forms
from django.forms import ModelForm
from .models import deduction

class RequestForm(forms.ModelForm):
    # This is for the css or bootstrap.
    required_css_class = 'required'
    class Meta:
        model = deduction
        fields = [
            'formula', 'resolve_type'
        ]

wang/pages/views.py
#AUTHORS:

#Gabriel Lizano Alvarado
#Edwin Lobo Sánchez 
#Ruben Pereira Ugalde
#Luis Guillermo Ramírez Díaz

from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.http import JsonResponse
from .models import Page
from .forms import RequestForm
from datetime import datetime
import requests
import json

# Create your views here.

def index(request,pagename):
    # This is for return the page.html with the form.
    submitted = False
    approved = True
    form = RequestForm()
    return render(request,'pages/page.html', { 'form': form, 'page_list': Page.objects.all(), 
                    'submitted': submitted, 'approved': approved } )

def page_deductions(request):
    # This is for return the page2.html with the table with the
    # deductions.
    print("Inside page_deductions request.")
    dict = get_deductions()
    dict = list ( map(lambda x: dating(x), dict) )
    context = {
        "deductions" : dict
    }
    return render(request, "pages/page2.html", context)
    
def dating(data):
    new_date = data['created'][:19]
    new_date = new_date.replace('T',' ')
    data['created'] = new_date
    return data

# Method to verify if the expression have all the requirements to be
# evaluated.

def verify_in_api(data_post):
    # This use 201 if is created...
    r = requests.post('http://localhost:8080/api/deduction/', data = data_post)
    if r.status_code == 201:
        ded_json = r.json()
        return ded_json
    return False

# Methods that are used when I use AJAX.

@csrf_exempt
def request(request):
    if request.method == 'POST':
        deduc = verify_in_api(request.POST)
        if not deduc:
            return None
        return get_deduction_and_details(deduc.get('id'))

@csrf_exempt
def request_all_tree(request):
    a = request.POST.get('formula_id')
    return get_deduction_and_details(a)

# Methods for get the Deductions with the Web-API. 

def get_deductions():
    r = requests.get('http://localhost:8080/api/deduction/all')
    if r.status_code == 200:
        return r.json()
    return None

def get_deduction(id):
    r = requests.get(f'http://localhost:8080/api/deduction/{id}')
    if r.status_code == 200:
        return r.json()
    else:
        return False

# Methods for get all the details of the deduction.
# This are the new expressions that generates the proof testing.
        
def get_deduc_details(deduction_id):
    r = requests.get(f'http://localhost:8080/api/detail/spec/{deduction_id}')
    if r.status_code == 200:
        return r.json()
    else:
        return False

def get_deduction_and_details(id):
    r = requests.get(f'http://localhost:8080/api/deduction/{id}')
    if r.status_code == 200:
        deduc = r.json()
        details = get_deduc_details(deduc.get('id'))
        details.insert(0, deduc)
        return JsonResponse(json.dumps(details), safe = False)
    return None

wang/pages/templates/pages/page.html
<!-- #AUTHORS:

#Gabriel Lizano Alvarado
#Edwin Lobo Sánchez 
#Ruben Pereira Ugalde
#Luis Guillermo Ramírez Díaz -->

{% extends "base.html" %}
{%block title%} {{title}}{%endblock title%}
{% block content %}
<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">
            {{ form.as_table }}
            <tr>
                <td colspan = "2" align="center" >
                <button id= "but" class="btn btn-info" type="submit">Evaluate</button>
                </td>
            </tr>
            <tr id ="fail" style="display:none"> 
                <td class="alert alert-danger" role="alert" colspan = "2" align="center">
                     Syntax-Error.
                </td>
            </tr>
        </table></br>
        {% csrf_token %}
        <div id= "progressbar" class="progress">
            <div id="prog" class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">
                We are proccesing your request. Just wait a few seconds.
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div id="chart_head" class="text-center"></div>
    </div>
</div>
<div class="row">
    <div class="col-12">
    <div id="chart_div" style="margin-bottom: 50px"></div>
</div>
{% endblock content %}
{% block javascript %}
    <script>
        $("#but").click(function () {
            $('#progressbar').show()
            $('#chart_head').hide()
            $('#chart_div').hide()
            $.ajax({
                url: 'ajax/request',
                type: 'POST',
                data: {
                    'formula': $('#id_formula').val(),
                    'resolve_type' : $('#id_resolve_type').val()
                },
                dataType: 'json',
                success: function (data) {
                    if (data) {
                        $('#fail').hide()
                        drawChart(data);
                        $('#progressbar').hide()
                        $('#chart_head').show()
                        $('#chart_div').show()
                    }
                },
                error: function(){
                    $('#progressbar').hide()
                    $('#fail').show()
                }

            });
        });
    </script>
{% endblock javascript %}

wang/pages/templates/pages/page2.html
<!-- #AUTHORS:

#Gabriel Lizano Alvarado
#Edwin Lobo Sánchez 
#Ruben Pereira Ugalde
#Luis Guillermo Ramírez Díaz -->

{% extends "base.html" %}
{%block title%} Deduction's record {%endblock title%}
{% block content %}
<div class="row">
    <div class="col-md-8 offset-md-2">
    <div class ="table-wrapper-scroll-y">
        <table class="table table-bordered">
            <thead class="thead-light">
                <tr>
                    <th colspan="4" align="center">Deduction's record</th>
                <tr>
            </thead>
            <tr>
                <th scope="col" align="center">Id</td>
                <th scope="col">Formula</td>
                <th scope="col">Resolve Type</td>
                <th scope="col">Created</td>
            </tr>
            <tbody id="row">
                {% for data in deductions %}
                <tr>
                    <th align="center" id="{{data.id}}">{{data.id}}</th>
                    <td id="{{data.id}}">{{data.formula}}</td>
                    <td id="{{data.id}}">{{data.resolve_type}}</td>
                    <td id="{{data.id}}">{{data.created}}</td>
                </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <th colspan="4" align="center">End</th>
                <tr>
            </tfoot>
        </table>
        </div></br>
        {% csrf_token %}
        <div id= "progressbar" class="progress">
            <div id="prog" class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">
                We are proccesing your request. Just wait a few seconds.
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div id="chart_head" class="text-center"></div>
    </div>
</div>
<div class="row">
    <div class="col-12">
    <div id="chart_div" style="margin-bottom: 50px"></div>
</div>
{% endblock content %}

{% block javascript %}
    <script>
        $("#row").click(function (e) {
            var id = e.target.id;
            $('#progressbar').show()
            $('#chart_head').hide()
            $('#chart_div').hide()
            $.ajax({
                url: 'ajax/request_all_tree',
                type: 'POST',
                data: {
                    'formula_id' : id,
                    'csrfmiddlewaretoken': '{{csrf_token}}'
                },
                dataType: 'json',
                success: function (data) {
                    if (data) {
                        $('#progressbar').hide()
                        drawChart(data);
                        $('#chart_head').show()
                        $('#chart_div').show()
                    }
                },
                error: function(){
                    alert("Something is wrong....")
                }

            });
        });
    </script>
{% endblock javascript %}

wang/wang/templates/base.html
<!-- #AUTHORS:

#Gabriel Lizano Alvarado
#Edwin Lobo Sánchez 
#Ruben Pereira Ugalde
#Luis Guillermo Ramírez Díaz
 -->
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            Untitled Document
        {% endblock title %}
    </title>
    <link href="{% static 'main.css' %}" rel="stylesheet" type="text/css">
    <link rel="shortcut icon" href="{%static 'favicon.png'%}">
    <script src="{% static 'google_charts.js' %}" type="text/javascript"></script>
    <script src="{% static 'scripts.js' %}" type="text/javascript"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
</head>

<body>
    <div id="container-fluid">
        <header>
            <nav id="mynavbar "class="navbar navbar-expand-lg navbar navbar-dark bg-primary">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                    <a class="navbar-brand">Theorems</a>
                    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                      <li class="nav-item active">
                        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="./page_deductions">History</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" data-toggle="modal" data-target="#authorsModal">Authors</a>
                      </li>
                    </ul>
                </div>
            </nav>
        </header>
        <div class="container">
            {% block content %}{% endblock content %}
        </div>
    </div>
    <!-- Modal for authors. -->
    <div class="modal fade" id="authorsModal" tabindex="-1" role="dialog" aria-labelledby="authorsModalTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="authorsModalTitle">Authors</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    This project was developed by Team #03: </br>
                    Gabriel Lizano Alvarado </br>
                    Edwin Daniel Lobo Sánchez </br>
                    Rubén Pereira Ugalde </br>
                    Luis Guillermo Ramírez Díaz </br></br>
                    Professor: </br>
                    Dr. Carlos Loría-Sáenz </br></br>
                    National University, Heredia, Costa Rica, 2018</br>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</body>
<footer class="footer">Copyright &copy; 2018 Programming Paradigms</footer>
{% block javascript %}{% endblock javascript %}
</html>